#!/usr/bin/env ruby

branch = `git branch | grep '*'`.chomp.sub('* ', '')
commit = File.readlines(ARGV[0])

if ARGV.length==0
  return
end

index = commit[0].index(branch)
if index != nil && index == 0
  commit[0] = commit[0].sub(/^#{branch}\s/, "")
end

open(ARGV[0], 'w') {|file|
  file.print "#{branch} "
  file.puts commit
}

